#define MAX_LABEL_LEN 31
#define MACRO_START "macr" /* Macro start keyword */
#define MACRO_END "end_macr"
#define MAX_FILE_NAME 100
#define MAX_MEMORY_WORDS 4096

#define DATA_DIRECTIVE ".data"
#define STRING_DIRECTIVE ".string"
#define EXTERN_DIRECTIVE ".extern"
#define ENTRY_DIRECTIVE ".entry"

#define BINARY_CODE_LEN 15
#define OP_CODE_ARRAY_SIZE 16

#define BITWISE_SHIFT_LEFT_A 2
#define BITWISE_SHIFT_LEFT_R 1
#define BITWISE_SHIFT_LEFT_E 0
#define BITWISE_SHIFT_LEFT_OPCODE 11
#define BITWISE_SHIFT_LEFT_DEST_MIUN 3
#define BITWISE_SHIFT_LEFT_SRC_MIUN 7
#define BITWISE_SHIFT_LEFT_NUM_WORD 3
#define BITWISE_SHIFT_LEFT_DEST_REGISTER 3
#define BITWISE_SHIFT_LEFT_SRC_REGISTER 6
#define BITWISE_SHIFT_LEFT_ADDRESS 3